# Generated by Django 4.1.4 on 2023-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(to='userprofile.userpost'),
        ),
        migrations.AddField(
            model_name='user',
            name='some_field',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
