# Generated by Django 4.1.4 on 2022-12-24 09:34

from django.db import migrations, models
import userprofile.utils


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='Nothing', max_length=500, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.IntegerField(blank=True, default=0, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('G', 'Gay'), ('L', 'Lesbian'), ('B', 'Bisexual')], max_length=1, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, validators=[userprofile.utils.validation_of_number], verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_study',
            field=models.CharField(blank=True, default='Undefind', max_length=200, verbose_name='Study place'),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_work',
            field=models.CharField(blank=True, default='Undefind', max_length=200, verbose_name='Work place'),
        ),
    ]
