# Generated by Django 4.1.4 on 2023-01-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_user_posts_user_some_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='some_field',
        ),
    ]
