# Generated by Django 4.1.4 on 2023-01-01 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_user_favorite_books_user_favorite_movies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentToUserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commented_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.photo')),
            ],
        ),
    ]
