# Generated by Django 4.1.4 on 2023-01-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('avatar', models.ImageField(upload_to='media/community_avatars')),
                ('theme', models.CharField(blank=True, choices=[('Undefind', 'Undefind'), ('Music', 'Music'), ('Sport', 'Sport'), ('Games', 'Games'), ('Social', 'Social'), ('Politic', 'Politic'), ('Culture', 'Culture'), ('Education', 'Education')], default='Undefind', max_length=50)),
                ('sub_theme', models.CharField(blank=True, default='Undefind', max_length=50)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ('theme', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/community_posts_photo')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('writer',),
            },
        ),
    ]
