# Generated by Django 4.1.4 on 2022-12-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='role',
            field=models.CharField(choices=[('Participant', 'Participant'), ('Worker', 'Worker'), ('Owner', 'Owner')], default='Participant', max_length=50),
        ),
    ]
