# Generated by Django 4.1.4 on 2022-12-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_followers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='role',
            field=models.CharField(blank=True, choices=[('Participant', 'Participant'), ('Worker', 'Worker'), ('Owner', 'Owner')], default='Participant', max_length=50),
        ),
    ]
